# Docker Compose for the EDA architecture
# Runs Mosquitto (MQTT broker), Kafka broker, and an MQTT subscriber service.

services:
# MQTT Broker
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    volumes: 
      - ./configs/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data/mosquitto:/mosquitto/data
      - ./log/mosquitto:/mosquitto/log
    ports:
      - "1883:1883"  
      - "9001:9001"  # WebSocket port

    # to interact with command line
    stdin_open: true
    tty: true

    restart: unless-stopped # avoids to restart on manual stop
  # MQTT Subscriber
  mqtt_subscriber:
    build: ./services/mqtt_kafka_bridge
    container_name: mqtt_subscriber
    depends_on:
      mosquitto:
        condition: service_started
      broker:
        condition: service_healthy
    env_file:
      - ./services/mqtt_kafka_bridge/.env
    restart: unless-stopped

  # Kafka Broker
  broker:
    image: apache/kafka:latest
    container_name: broker
    hostname: broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - ./data/kafka:/var/lib/kafka/data
      - ./log/kafka:/var/lib/kafka/logs
    healthcheck:
      test: ["CMD", "bash", "-c", "nc -z localhost 9092"]
      interval: 10s
      timeout: 5s
      retries: 5


# Custom network for the EDA architecture
networks:
  default:
    name: eda_network